title: text.mainframe.computer
author:
email: hey@mainframe.computer
description: > # this means to ignore newlines until "show_exerpts:"
  Thoughts on digital harm-reduction.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 15
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  #disqus:
    #shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://mastodon.social/@matrix8967
      icon: mastodon
      color: cyan
    # - url: https://matrix8967.itch.io
    #   icon: itch-io
    #   color: red
    - url: https://gitlab.com/matrix8967
      icon: gitlab
      color: purple

  show_author: true

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: gitlab
gitlab_username: matrix8967
